server:
  port: 9000

sendgrid:
  mail:
    template: >
      {"personalizations":[{"to":[{"email":"<TOEMAIL>"} <toEmail>],"subject":"Contact information from -> <subject> "}],"from":{"email":"<FROMEMAIL>"},"content":[{"type":"text/plain","value": "<body>"}]}
    toAdd: >
      ,{"email":"<email>"}