server:
  port: 9000

spring:
  application:
    name: ms-mailer

logging:
  path: ../
  file:
    name: ${logging.path}/${spring.application.name}.log
    pattern:
      file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'

sendgrid:
  mail:
    template: >
      {"personalizations":[{"to":[{"email":"<TOEMAIL>"} <toEmail>],"subject":"Contact information from -> <subject> "}],"from":{"email":"<FROMEMAIL>"},"content":[{"type":"text/plain","value": "<body>"}]}
    toAdd: >
      ,{"email":"<email>"}